-- 11. Top 5 Customers by Revenue: Write a query to find the top 5 customers based on total revenue generated from their orders.

select cust_id, sum(total_price) AS total_revenue 
from pizaa_sales.orders 
group by cust_id 
order by total_revenue DESC LIMIT 5;

-- 12. Monthly Sales Trends: Write a query to generate a report showing the total sales for each month in 2024.

select month(orderdate) AS month, SUM(order_id) AS total_sales
from pizaa_sales.orders
group by month(orderdate)
order by month;

-- 13. Staff Order Processing: Write a query to find out which staff member has processed the most orders.

select COUNT(o.order_id) AS totalOrders, o.staff_id, 
       CONCAT(s.fName, ' ', s.lName) AS fullName 
from pizaa_sales.orders AS o 
JOIN pizaa_sales.staff AS s on o.staff_id = s.staff_id 
group by o.staff_id, s.fName, s.lName 
order by totalOrders DESC LIMIT 1;

-- 14. Write a query to determine which staff members have sold the most expensive pizzas to identify high performers. 

select s.staff_id, p.pizzaType, p.PricePerUnit, CONCAT(s.fName, ' ', s.lName) AS fullName
from pizaa_sales.orders AS o
JOIN pizaa_sales.pizza AS p ON o.pizza_id = p.pizza_id
JOIN pizaa_sales.staff AS s ON o.staff_id = s.staff_id
order by p.PricePerUnit DESC LIMIT 1;

-- 15. Write a query to find staff members who haven't processed any orders to evaluate their performance.

select o.staff_id, CONCAT(s.fName, ' ', s.lName) AS fullName
from pizaa_sales.orders AS o
JOIN pizaa_sales.staff AS s ON o.staff_id = s.staff_id
where o.order_id IS NULL;

-- 16. Write a query to identify which pizza is sold the most to optimize inventory and marketing efforts.

select p.pizzaType, count(o.order_id) AS totalOrders
from pizaa_sales.orders AS o
JOIN pizaa_sales.pizza AS p ON o.pizza_id = p.pizza_id
group by p.pizzatype
order by totalOrders desc LIMIT 1;

-- 17. Write a query to determine how much revenue each staff member has generated by processing orders.

select o.staff_id, CONCAT(s.fName, ' ', s.lName) AS fullName, sum(o.total_price) as total_revenue
from pizaa_sales.orders AS o
JOIN pizaa_sales.staff AS s ON o.staff_id = s.staff_id
group by s.fName, s.lName, o.staff_id
order by total_revenue DESC;

-- 18. Write a query to identify which pizzas are the least popular and which staff members have sold them, to adjust strategy.

select p.PizzaType, o.staff_id, count(o.order_id) AS totalOrders, CONCAT(s.fName, ' ', s.lName) AS fullName
from pizaa_sales.orders AS o
JOIN pizaa_sales.pizza AS p ON o.pizza_id = p.pizza_id
JOIN pizaa_sales.staff AS s ON o.staff_id = s.staff_id
group by p.PizzaType, fullName, o.staff_id
order by totalOrders ASC;

SELECT p.PizzaType, COUNT(o.order_id) AS total_orders, CONCAT(s.fName, ' ', s.lName) AS fullName
FROM pizaa_sales.orders AS o
INNER JOIN pizaa_sales.pizza AS p ON o.pizza_id = p.pizza_id
INNER JOIN pizaa_sales.staff AS s ON o.staff_id = s.staff_id
GROUP BY p.pizzatype, s.fName, s.lName
ORDER BY total_orders ASC;
